#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# License           : MIT
# Author            : Jingxin Fu <jingxinfu.tj@gmail.com>
# Date              : 27/01/2020
# Last Modified Date: 03/02/2020
# Last Modified By  : Jingxin Fu <jingxinfu.tj@gmail.com>
import os
__version__="0.10"


#Precompute data, to infer biomarker, infiltration....
PrepareData_R = os.path.join('Tigger', 'prepare_data', 'data_prepare.R')
PrepareData_Py = os.path.join('Tigger', 'prepare_data', 'data_prepare.py')

#Immune related CRISPR SCREEN
R_RMD = os.path.join('Tigger', 'evaluator', 'InvokeR.R')

#################### FIGURE SETTING ####################
Figure_Style='paper'
#################### Immune cell type SETTING ####################
BIOMARKER_SETTING = {
        "cluster":{
            "MDSC": "1. Immune suppressive",
            "TAM M2": "1. Immune suppressive",
            "CAF":"1. Immune suppressive",
            "CD274 Expression": "2. Cytotoxicity",
            "CTL": "2. Cytotoxicity",
            "Cytokine Cytokine Receptor Interaction": "2. Cytotoxicity",

            "Antigen Processing and Presentation": "3. Presentation",
            "Antigen Presentation By MHCI": "3. Presentation",
            "Surface gene (ligand)":"3. Presentation",
            "Surface gene (receptor)":"3. Presentation",

            "IRF3 Mediated TypeI Induction":"3. Immunogenicity",
            "MSI Score":"3. Immunogenicity",
            "P53 Pathway":"3. Immunogenicity",

            "Dysfunction":"4. Dysfunction",
            "Exclusion":"4. Dysfunction",
            "TIDE":"4. Dysfunction",

            "IFNG Signature":"5. IFNG",
            "Interferon Alpha Response":"5. IFNG",
            "Interferon Gamma Response":"5. IFNG",
            "Inflammatory Response": "5. IFNG",
            "ISG Signature":"5. IFNG",
            #"Cytokine":"Immune effector",
            #"GZMB_div_CD8A":"Immune effector",
        }
}
BIOMARKER_SETTING_V2 = {
    "cluster":{
        "CD274 Expression":"Immune suppressive 1",
        "PDCD1 Expression":"Immune suppressive 2",
        "IFNG Signature":"Immune suppressive 3",
        "Antigen Processing and Presentation":"Immune activate 1",
        "Antigen Presentation By MHCI":"Immune activate 2",
        "Cytokine Cytokine Receptor Interaction":"Immune effector 1",
        "IFN-stimulated Signature":"Immune suppressive 4",
        "Surface gene (ligand)":"Immune activate 3",
        "Surface gene (receptor)":"Immune activate 4",
        "MSI":"Immune activate 5",
        "DNA Repair":"Immune activate 6",
        "P53 Pathway":"Immune activate 7",
        "TMB":"Immune activate 8",
        "IRF3 Mediated TypeI Induction":"Immune activate 91",
        "Interferon Alpha Response":"Immune suppressive 5",
        "Interferon Gamma Response":"Immune suppressive 6",
        "IFNG Pathway Genes":"Immune suppressive 7",
        "Doubling time (hrs)":"Immune activate 9",
        "Inflammatory Response":"Immune effector 2",
        }
}

CELL_TYPE_SETTING = {
    "order" :[
            "CD4 T Cell",
            "Tregs",
            "CD8 T Cell",
            "B Cell",
            "NK Cell",
            "Neutrophil",
            "Macrophage",
            "Macrophage M0",
            "Macrophage M1",
            "Macrophage M2",
            "Macrophage/Monocyte",
            "Cancer Associated Fibroblast",
            "Myeloid Dendritic Cell",
            "Plasmacytoid Dendritic Cell",
            "Mast Cell",
            "Monocyte",
            "Endothelial Cell",
            "Eosinophil Cell",
            "Gamma Delta T Cell",
            "T NK Cell",
            "Lymphoid Progenitor",
            "Myeloid Progenitor",
            "Granulocyte-monocyte Progenitor",
            "Hematopoietic Stem Cell",

    ],
    "cluster":{
        "B cell_EPIC":"B Cell",
        "B cell_MCP_COUNTER": "B Cell",
        "B cell memory_CIBERSORT":"B Cell",
        "B cell memory_CIBERSORT-ABS": "B Cell",
        "B cell memory_XCELL": "B Cell",
        "B cell naive_CIBERSORT": "B Cell",
        "B cell naive_CIBERSORT-ABS": "B Cell",
        "B cell naive_XCELL": "B Cell",
        "B cell plasma_CIBERSORT": "B Cell",
        "B cell plasma_CIBERSORT-ABS": "B Cell",
        "B cell plasma_XCELL": "B Cell",
        "B cell_QUANTISEQ": "B Cell",
        "B cell_TIMER": "B Cell",
        "B cell_XCELL": "B Cell",
        "Class-switched memory B cell_XCELL":"B Cell",
        "Cancer associated fibroblast_EPIC": "Cancer Associated Fibroblast",
        "Cancer associated fibroblast_MCP_COUNTER": "Cancer Associated Fibroblast",
        "Cancer associated fibroblast_XCELL": "Cancer Associated Fibroblast",
        "Common lymphoid progenitor_XCELL": "Lymphoid Progenitor",
        "Common myeloid progenitor_XCELL": "Myeloid Progenitor",
        "Granulocyte-monocyte progenitor_XCELL": "Granulocyte-monocyte Progenitor",
        "Endothelial cell_EPIC": "Endothelial Cell",
        "Endothelial cell_MCP_COUNTER": "Endothelial Cell",
        "Endothelial cell_XCELL": "Endothelial Cell",
        "Eosinophil_CIBERSORT": "Eosinophil Cell",
        "Eosinophil_CIBERSORT-ABS": "Eosinophil Cell",
        "Eosinophil_XCELL": "Eosinophil Cell",
        "Hematopoietic stem cell_XCELL": "Hematopoietic Stem Cell",
        "Macrophage_EPIC": "Macrophage",
        "Macrophage_TIMER": "Macrophage",
        "Macrophage_XCELL": "Macrophage",
        "Macrophage M0_CIBERSORT": "Macrophage M0",
        "Macrophage M0_CIBERSORT-ABS": "Macrophage M0",
        "Macrophage M1_CIBERSORT": "Macrophage M1",
        "Macrophage M1_CIBERSORT-ABS": "Macrophage M1",
        "Macrophage M1_QUANTISEQ": "Macrophage M1",
        "Macrophage M1_XCELL": "Macrophage M1",
        "Macrophage M2_CIBERSORT": "Macrophage M2",
        "Macrophage M2_CIBERSORT-ABS": "Macrophage M2",
        "Macrophage M2_QUANTISEQ": "Macrophage M2",
        "Macrophage M2_XCELL": "Macrophage M2",
        "Macrophage/Monocyte_MCP_COUNTER": "Macrophage/Monocyte",
        "Mast cell activated_CIBERSORT":"Mast Cell",
        "Mast cell activated_CIBERSORT-ABS": "Mast Cell",
        "Mast cell resting_CIBERSORT": "Mast Cell",
        "Mast cell resting_CIBERSORT-ABS": "Mast Cell",
        "Mast cell_XCELL": "Mast Cell",
        "Monocyte_CIBERSORT": "Monocyte",
        "Monocyte_CIBERSORT-ABS": "Monocyte",
        "Monocyte_MCP_COUNTER":"Monocyte",
        "Monocyte_QUANTISEQ": "Monocyte",
        "Monocyte_XCELL":"Monocyte",
        "Myeloid dendritic cell activated_CIBERSORT": "Myeloid Dendritic Cell",
        "Myeloid dendritic cell activated_CIBERSORT-ABS": "Myeloid Dendritic Cell",
        "Myeloid dendritic cell activated_XCELL": "Myeloid Dendritic Cell",
        "Myeloid dendritic cell_MCP_COUNTER": "Myeloid Dendritic Cell",
        "Myeloid dendritic cell_QUANTISEQ": "Myeloid Dendritic Cell",
        "Myeloid dendritic cell resting_CIBERSORT": "Myeloid Dendritic Cell",
        "Myeloid dendritic cell resting_CIBERSORT-ABS": "Myeloid Dendritic Cell",
        "Myeloid dendritic cell_TIMER": "Myeloid Dendritic Cell",
        "Myeloid dendritic cell_XCELL": "Myeloid Dendritic Cell",
        "Neutrophil_CIBERSORT": "Neutrophil",
        "Neutrophil_CIBERSORT-ABS": "Neutrophil",
        "Neutrophil_MCP_COUNTER": "Neutrophil",
        "Neutrophil_QUANTISEQ": "Neutrophil",
        "Neutrophil_TIMER": "Neutrophil",
        "Neutrophil_XCELL": "Neutrophil",
        "NK cell activated_CIBERSORT":"NK Cell",
        "NK cell activated_CIBERSORT-ABS": "NK Cell",
        "NK cell_EPIC": "NK Cell",
        "NK cell_MCP_COUNTER": "NK Cell",
        "NK cell_QUANTISEQ": "NK Cell",
        "NK cell resting_CIBERSORT": "NK Cell",
        "NK cell resting_CIBERSORT-ABS": "NK Cell",
        "NK cell_XCELL": "NK Cell",
        "T cell NK_XCELL": "T NK Cell",
        "Plasmacytoid dendritic cell_XCELL": "Plasmacytoid Dendritic Cell",
        "T cell CD4+ central memory_XCELL":"CD4 T Cell",
        "T cell CD4+ effector memory_XCELL": "CD4 T Cell",
        "T cell CD4+_EPIC": "CD4 T Cell",
        "T cell CD4+ memory activated_CIBERSORT": "CD4 T Cell",
        "T cell CD4+ memory activated_CIBERSORT-ABS": "CD4 T Cell",
        "T cell CD4+ memory resting_CIBERSORT": "CD4 T Cell",
        "T cell CD4+ memory resting_CIBERSORT-ABS": "CD4 T Cell",
        "T cell CD4+ memory_XCELL": "CD4 T Cell",
        "T cell CD4+ naive_CIBERSORT": "CD4 T Cell",
        "T cell CD4+ naive_CIBERSORT-ABS":"CD4 T Cell",
        "T cell CD4+ naive_XCELL": "CD4 T Cell",
        "T cell CD4+ (non-regulatory)_QUANTISEQ": "CD4 T Cell",
        "T cell CD4+ (non-regulatory)_XCELL":"CD4 T Cell",
        "T cell CD4+ Th1_XCELL":"CD4 T Cell",
        "T cell CD4+ Th2_XCELL": "CD4 T Cell",
        "T cell CD4+_TIMER": "CD4 T Cell",
        "T cell follicular helper_CIBERSORT": "CD4 T Cell",
        "T cell follicular helper_CIBERSORT-ABS": "CD4 T Cell",
        "T cell CD8 + central memory_XCELL": "CD8 T Cell",
        "T cell CD8+_CIBERSORT": "CD8 T Cell",
        "T cell CD8+_CIBERSORT-ABS": "CD8 T Cell",
        "T cell CD8 + effector memory_XCELL": "CD8 T Cell",
        "T cell CD8+_EPIC": "CD8 T Cell",
        "T cell CD8+_MCP_COUNTER": "CD8 T Cell",
        "T cell CD8 + naive_XCELL": "CD8 T Cell",
        "T cell CD8+_QUANTISEQ": "CD8 T Cell",
        "T cell CD8+_TIMER": "CD8 T Cell",
        "T cell CD8+_XCELL": "CD8 T Cell",
        "T cell gamma delta_CIBERSORT":"Gamma Delta T Cell",
        "T cell gamma delta_CIBERSORT-ABS":"Gamma Delta T Cell",
        "T cell gamma delta_XCELL": "Gamma Delta T Cell",
        "T cell regulatory(Tregs)_CIBERSORT":"Tregs",
        "T cell regulatory(Tregs)_CIBERSORT-ABS": "Tregs",
        "T cell regulatory(Tregs)_QUANTISEQ": "Tregs",
        "T cell regulatory(Tregs)_XCELL": "Tregs",
    }
}

